---
title: "STA210 Final Project"
author: "Aryan Mathur, Molly Honecker"
format: pdf
---

### Introduction

```{r libraries, message = F, warning = F}

library(tidyverse)
library(tidymodels)
library(lme4)
library(lubridate)
library(broom)
library(leaps)
library(MASS)
library(caret)
library(glmnet)
library(Stat2Data)
library(nnet)
library(ggfortify)
library(gee)

baseball <- read_csv("baseball.csv")
colnames(baseball) <- gsub(" ", "_", colnames(baseball))
colnames(baseball) <- tolower(colnames(baseball))

baseball$month <- month(as.Date(baseball$date))
baseball$score_diff <- baseball$home_team_score - baseball$visiting_team_score
baseball$home_win <- ifelse(baseball$home_team_score > baseball$visiting_team_score, 1, 0)

baseball <- baseball[!is.na(baseball$attendance),]

sum(is.na(baseball$attendance))

```

```{r vars, message = F, error = F}

baseball <- baseball %>%
  mutate(yanks = ifelse(home_team == "NYA", 1, 0))

baseball <- baseball %>%
  mutate(extras = ifelse(length_of_game_outs > 54, 1, 0))

```

INSERT EXPLORATORY HERE!!!!!!!!!!!!!


```{r model, message = F, warning = F}

m6 <- glmer(home_win ~ 1 + attendance + day_night_indicator + extras +
              day_of_week + game_number + as.factor(month) + home_league + (1 | home_team),
          data = baseball,
          family = 'binomial')

summary(m6)

```

```{r lasso, message = F, error = F}

set.seed(999)
y <- baseball$home_win
x <- model.matrix(home_win ~ 1 + attendance + day_night_indicator + extras +
              day_of_week + game_number + as.factor(month) + home_league,
                  data = baseball, family='binomial')

m_lasso_cv <- cv.glmnet(x, y, alpha = 1)

best_lambda <- m_lasso_cv$lambda.min
m_best <- glmnet(x, y, alpha = 1, lambda = best_lambda)
m_best$beta 

```

```{r model, message = F, warning = F}

m7 <- glmer(home_win ~ 1 + attendance + day_of_week + 
              as.factor(month) + (1 | home_team),
          data = baseball,
          family = 'binomial')

summary(m7)

```

```{r}

emplogitplot1(home_win ~ attendance, data = baseball, ngroups = 100)

```

```{r, message = F, error = F}

baseballpreddata <- baseball[, c("attendance", "day_of_week", "month", "home_team")]

jvalues <- with(baseball, seq(from = min(attendance), to = max(attendance), length.out = 100))

# calculate predicted probabilities and store in a list
pp <- lapply(jvalues, function(j) {
    baseballpreddata$attendance <- j
    predict(m7, newdata = baseballpreddata, type = "response")
})

```

```{r}

# get the means with lower and upper quartiles
plotdat <- t(sapply(pp, function(x) {
    c(M = mean(x), quantile(x, c(0.25, 0.75)))
}))

# add in LengthofStay values and convert to data frame
plotdat <- as.data.frame(cbind(plotdat, jvalues))

colnames(plotdat) <- c("PredictedProbability", "Lower", "Upper", "Attendance")

plotdat

ggplot(plotdat, aes(x = Attendance, y = PredictedProbability)) + 
  geom_linerange(aes(ymin = Lower, ymax = Upper)) + 
  geom_line(size = 2) + ylim(c(0, 1))

```





